image: dlp

stages:
- cours
- tme


ILP1:
  stage: cours
  script: >
    /home/dlp/run.sh -id ILP1 -name ILP1
    com.paracamplus.ilp1.tools.test.FileToolTest
    com.paracamplus.ilp1.interpreter.test.InterpreterTest
    com.paracamplus.ilp1.compiler.test.CompilerTest
  artifacts:
    reports:
      junit: report.xml

ILP2:
  stage: cours
  script: >
    /home/dlp/run.sh -id ILP2 -name ILP2
    com.paracamplus.ilp2.interpreter.test.InterpreterTest
    com.paracamplus.ilp2.compiler.test.CompilerTest
  artifacts:
    reports:
      junit: report.xml

TME4:
  stage: tme
  script: >
    /home/dlp/run.sh -id TME4 -name TME4
    com.paracamplus.ilp2.ilp2tme4.interpreter.test.InterpreterTest
    com.paracamplus.ilp2.ilp2tme4.compiler.test.CompilerTest
  artifacts:
    reports:
      junit: report.xml

TME5:
  stage: tme
  script: >
    /home/dlp/run.sh -id TME5 -name TME5
    com.paracamplus.ilp2.ilp2tme5.interpreter.test.InterpreterTest
    com.paracamplus.ilp2.ilp2tme5.compiler.test.CompilerTest
  artifacts:
    reports:
      junit: report.xml

TME5bis:
  stage: tme
  script: >
    /home/dlp/run.sh -id TME5bis -name TME5bis
    com.paracamplus.ilp2.ilp2tme5bis.interpreter.test.InterpreterTest
    com.paracamplus.ilp2.ilp2tme5bis.compiler.test.CompilerTest
  artifacts:
    reports:
      junit: report.xml

TME6:
  stage: tme
  script: >
    /home/dlp/run.sh -id TME6 -name TME6
    com.paracamplus.ilp2.ilp2tme6.interpreter.test.InterpreterTest
    com.paracamplus.ilp2.ilp2tme6.compiler.test.CompilerTest
  artifacts:
    reports:
      junit: report.xml